### PR TITLE
Document Reset

### PR DESCRIPTION
**Pull request by jackkoenig**
This isn't currently using `mdoc` so that is a desirable improvement. In any case, this is originally the work of @mwachs5 that I edited and extended a bit. Thank you very much @mwachs5!

### CODE REVIEW

**Comment by mwachs5** [comment]
hi. folks, what can i do to get this merged and live on the web?

**Comment by jackkoenig** [comment]
see Schuyler's comments here: https://github.com/jackkoenig/www.chisel-lang.org/pull/2. We were going to need to split it in 2 but we think we might just publish the website for version 3.3.0-RC1 and thus not have to split it up. I *do* think that we should add notes to the doc like: _New in v3.3.0_

**Comment by seldridge** [comment]
Yeah, I'm fine to merge it with:

1. A link in `docs/src/main/resources/microsite/data/menu.yml`
2. `mdoc` code fences
3. Fixes so that the `mdoc` code fences compile

The website is now on 3.3.0-RC1, so there's no need to kludge around the fact that `RequireAsyncReset` and `RequireSyncReset` no longer exist (see: https://github.com/jackkoenig/www.chisel-lang.org/pull/2/files#diff-43dde1efe9b15166570edf91791e2fc5R13-R18). Highlighting when things were added is a good suggestion, too.

**Comment by jackkoenig** [comment]
@seldridge I merged your changes, rebased on master, and then made a few more changes (reflected in "Further improvements to reset.md").

In updating the documentation I realized there is _supposed_ to be a better way to Force a reset type (that even could obviate the need for the top-level `reset` being of type `Bool`). Anyway I will try to get it fixed for `3.3.1` (and maybe `3.2.6`).

**Comment by jackkoenig** [comment]
> Consider removing the "New in Chisel 3.3.0".

I thought it might be useful to have such things for a while. Especially because I want to get a fix in to 3.3.1 that provides a better way to do `Forcing Reset Type` and would thus be "New in Chisel 3.3.1" (although also potentially backported to 3.2.6). What do you think? I could be convinced to remove it.

**Comment by seldridge** [comment]
Im good with keeping it in.

**Pull request merged**
